// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuppliesWebApplication.Infrastructure;

#nullable disable

namespace SuppliesWebApplication.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250717151753_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuppliesWebApplication.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_registration");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("Stamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("stamp");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_offers");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_offers_supplier_id");

                    b.ToTable("offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 1",
                            Stamp = "Марка 1",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 2",
                            Stamp = "Марка 2",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 3",
                            Stamp = "Марка 3",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 4",
                            Stamp = "Марка 4",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 5",
                            Stamp = "Марка 5",
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 6",
                            Stamp = "Марка 6",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 7",
                            Stamp = "Марка 7",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 8",
                            Stamp = "Марка 8",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 9",
                            Stamp = "Марка 9",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 10,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 10",
                            Stamp = "Марка 10",
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 11,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 11",
                            Stamp = "Марка 11",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 12,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 12",
                            Stamp = "Марка 12",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 13,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 13",
                            Stamp = "Марка 13",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 14,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 14",
                            Stamp = "Марка 14",
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 15,
                            DateRegistration = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Model = "Модель 15",
                            Stamp = "Марка 15",
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("SuppliesWebApplication.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_create");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreate = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Name = "Поставщик 1"
                        },
                        new
                        {
                            Id = 2,
                            DateCreate = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Name = "Поставщик 2"
                        },
                        new
                        {
                            Id = 3,
                            DateCreate = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Name = "Поставщик 3"
                        },
                        new
                        {
                            Id = 4,
                            DateCreate = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Name = "Поставщик 4"
                        },
                        new
                        {
                            Id = 5,
                            DateCreate = new DateTime(2025, 7, 17, 16, 40, 17, 0, DateTimeKind.Local),
                            Name = "Поставщик 5"
                        });
                });

            modelBuilder.Entity("SuppliesWebApplication.Domain.Entities.Offer", b =>
                {
                    b.HasOne("SuppliesWebApplication.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offers_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
